# nginx/node-mvc.conf
server {
    listen 80;
    server_name localhost;
    root /workspaces/node-mvc/public;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ = 404;
    }
}
